### ISSUE TITLE
Add recover in ipfs mount command.

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#124]
Ive found that if ipfs panics for any reason (as rare as that might be) the fuse stuff gets into a funky state since it wasnt properly dismounted, i wanted to discuss the pros and cons of having a recover statement in the ipfs mount command to catch those and safely unmount any mounted fuse systems.

**Comment by cryptix** [comment]
I think we tackled most of these in #945 and can close this for now?

cc @whyrusleeping reopen if I missed something.

**Comment by whyrusleeping** [comment]
Ah, im fine with closing this. but this wasnt about race conditions, it was about fuse not being unmounted properly in the case of a panic

**Comment by cryptix** [comment]
Oh... I switched cause and outcome here than.

I wonder where a `recover()` could be placed. It would have to be somewhere blocking for ipfs to exit, right? The `mount` core command wouldn't work for that since they return to early.

**Comment by whyrusleeping** [comment]
Yeah, i wasnt sure where to put it, which is why i never got around to doing it, lol
