### ISSUE TITLE
Provide default object hashesto explore/demo

### ISSUE THREAD

**Issue by patcon** [jbenet/go-ipfs#164]
I'm attempting to experiment with go-ipfs, but am not sure how to tell when I have it set up correctly. It might be nice if there were some hashes for default objects that people could explore as they're diving in.

Ref: [IRC](https://botbot.me/freenode/ipfs/2014-10-13/?msg=23407258&page=2)

**Comment by jbenet** [comment]
This is fixed in https://github.com/jbenet/go-ipfs/pull/639
