### ISSUE TITLE
fix(peer) derive public key from private key

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#220]
In `WithKeyPair`, public key is passed in with private key and then compared.

TODO simply derive public from private.

see https://github.com/jbenet/go-ipfs/commit/9ca87fbb936729881d87ba0c36beb03b9a00ade8#commitcomment-8313740

**Comment by whyrusleeping** [comment]
I think this one can be closed, we no longer use `WithKeyPair`
