### ISSUE TITLE
command: ipfs ping <peer.ID>

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#229]
We need a command to ping nodes. The command should:

- find the node (in the routing system)
- connect to it
- send pings to that node, wait for pongs, and print out RTT time (just like `ping <ip addr>`)

```sh
# can specify address
> ipfs ping /ip4/1.2.3.4/tcp/4001/QmUGTUcHSEHNCuMdVTmAzdG6ooybb24RU6bN2i75yXX2vm

# or use the routing system to discover it
> ipfs ping QmUGTUcHSEHNCuMdVTmAzdG6ooybb24RU6bN2i75yXX2vm
Ping /ip4/1.2.3.4/tcp/4001/QmUGTUcHSEHNCuMdVTmAzdG6ooybb24RU6bN2i75yXX2vm
Pong 0 time=13.254 ms
Pong 1 time=30.766 ms
^C
--- ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 13.254/22.010/30.766/8.756 ms
```

or something like that.

**Comment by jbenet** [comment]
@whyrusleeping is working on this now

**Comment by whyrusleeping** [comment]
@jbenet until we get the ability to allow the user to cancel commands, ping is just going to run for a set number of times, which can be specified by a command line parameter. sound good?

**Comment by jbenet** [comment]
@whyrusleeping sound good!

**Comment by whyrusleeping** [comment]
ping is merged into master, closing
