### ISSUE TITLE
basic fuse set up in readme or link to wiki

### ISSUE THREAD

**Issue by ebuchman** [jbenet/go-ipfs#259]
As far as I can tell, fuse is the only thing making this project non purely "go-gettable". Of course it's fine if you don't want to mount, but everyone wants to mount, and I can see this being a staple problem for new users.

**Comment by whyrusleeping** [comment]
This issue (and associated PR) should get some love before the alpha, the guys from eris industries had a couple issues getting the fuse mounting to behave (aside from the recently addressed bugs). We might even go so far as to try and detect an issue for the user and print out helpful messages like "Your /etc/fuse.conf file has bad permissions" or "your user needs to be added to the 'fuse' group".
