### ISSUE TITLE
Bitswap peer receives duplicate blocks

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#261]
@whyrusleeping performed a bitswap test. 

1. Three nodes pin a widely available file.
2. Each node receives multiple copies of the file. (In his test, each received 20. Every partner that received the three nodes' want lists sent every block on it)

Some initial discussion occurred in IRC at #ipfs. Let's open discussion around the implementation of solutions for the various inefficiencies of the current implementation. Empirical and analytical approaches are both welcome. 

A couple initial idea come to mind:

* Instead of sending requests to each and every block provider (returned from the routing system), schedule requests to a small number and follow up with additional requests if necessary

* Instead of sending the local node's entire want list to each and every peer, partition the want list.

edited: with additional info from @whyrusleeping 

cc
@danmane

**Comment by whyrusleeping** [comment]
Im pretty sure i can mark this resolved, the latest changeset to bitswap has partially addressed this. (still not perfect, but better)
