### ISSUE TITLE
man pages

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#275]
Any real unixy tool worth its salt has verbose man pages, Personally, I love being able to just say 'man ThisFunctionImWorkingWith' and get help in my terminal.

There exist a few different solutions for generating man pages from godoc information, this will probably be good enough for us. (as long as they can do per function breakdowns!)
https://code.google.com/p/mango-doc/

**Comment by whyrusleeping** [comment]
closing old issues.

**Comment by jbenet** [comment]
we may still want real man pages someday -- agreed to close until then. (if people really need this poke us here!)

**Comment by anarcat** [comment]
poke.

**Comment by slang800** [comment]
+1 for man pages... (working on an Arch package to make installation easier, which traditionally comes with a `man` entry)

**Comment by jbenet** [comment]
we could generate them from the cli help

**Comment by whyrusleeping** [comment]
I'd love to have this... how does man work with subcommands?

**Comment by whyrusleeping** [comment]
It would be really cool to have a program/library that could accept one of the command objects from our commands lib and use it to generate a manpage.

**Comment by slang800** [comment]
@whyrusleeping: take a look at `man git` - that's a pretty well written manpage

@jbenet: probably not. the man page is supposed to explain the commands and workings of the program in depth. it would be better to generate it from the full documentation.

**Comment by unbeatable-101** [comment]
Poke

**Comment by rampaq** [comment]
Are there any manpages, yet? It would be really nice to have everything in one place.
