### ISSUE TITLE
dht query early exit bug

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#308]
I noticed a slight bug that probably hasnt caused any issues yet, but nonetheless, i beleive its a bug.
While running dhthell tests, i had one node do a 'put key val' and was presented the following messages:
```
21:43:08.365 ERROR    service: no request key [18 32 56 87 188 82 106 161 234 18 6 15 48 115 70 138 1 94 1 232 248 64 73 130 16 191 144 247 243 98 57 202 60 29 50 35 161 43] (timeout?) service.go:240
21:43:08.365 ERROR    service: no request key [18 32 84 248 159 180 219 214 155 152 31 80 88 56 55 235 130 185 4 148 136 244 0 39 99 23 238 207 187 125 101 171 241 133 53 93 58 177] (timeout?) service.go:240
```
Which up until now, i had been ignoring, but when i went to investigate what caused them, i found that as soon as a single 'PUT' query finished, we cancelled the context for all of them, causing their response handlers to be removed. Which, if we had any put queries that hadnt been run yet, would have caused our value to not have been propogated correctly (fortunately, our PUT operations all get sent out at the same time).

**Comment by jbenet** [comment]
@whyrusleeping is this still a problem?

**Comment by whyrusleeping** [comment]
This has been addressed and we should be able to close this one out
