### ISSUE TITLE
guarantee mutually exclusive access to persisted state

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#358]
As part of its normal operation, IPFS persists these items to disk:

* logs in `IPFS_DIR/logs/`
* a configuration file as `IPFS_DIR/config`
* a leveldb datastore in `IPFS_DIR/datastore/`

Collectively, we refer to these as the `repo`. 

**issue**
We wish to ensure that access to these resources is granted to just one process at a time.

While different mechanisms could be used to enforce mutually-exclusive access for each of the three resources, it may be simpler to provide a common mechanism to cover them all.

**proposal**
A good first step is to repurpose the `daemon.Lock` (lock file) as a `repo.Lock` or a `resource.Lock`. 

NB: This doesn't provide guarantees against callers who sidestep the Lock and go after the resources directly.

**Comment by jbenet** [comment]
@briantigerchow i believe this can be closed now? reopen if not.
