### ISSUE TITLE
introduce "repo" package to manage IPFS_DIR concerns

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#376]
**issue**

Introducing `daemon --init` broke `eventlog` configuration. Here's why:

1) Now, users may run `daemon` without an initialized repo.
2) the `configureLogger` hook checks to see whether the command `usesConfig` and `usesRepo`. If both are true, the logger is configured to use the IPFS_DIR. This is necessary since the logger logs to a file.

Since the daemon doesn't require a repo/config and configureLogger only runs if the upcoming command uses the config/repo, logs are not configured before running the daemon.

Notice that the one actual requirement for the hook is the existence of a config/repo.

Therefore, we should just check this property directly.

-- 

**proposal**

I propose we introduce a `repo` package to handle IPFS_DIR concerns. This would include the concern described in #358 (locking the repo).

Initially the package would have these exported functions:

- [ ] func IsInitialized bool
- [ ] func IsLocked bool
- [ ] func Lock *Lock

--

Also...

We've also discussed centralizing option precedence. ie. the logic that determines whether to use environment variables, user-provided CLI arguments, or config file values to determine the value of an option (eg. debug). This may be out of the scope of this issue.

**Comment by jbenet** [comment]
@briantigerchow is this ready to close? or things remaining?

**Comment by briantigerchow** [comment]
#578 closes this
