### ISSUE TITLE
Rename `IPFS_DIR` to `IPFS_PATH`

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#394]
Sounds more conventional.

**Comment by jbenet** [comment]
@briantigerchow thoughts?

**Comment by briantigerchow** [comment]
i'm indifferent. No serious harm will come in either case, but if we must commit to one, `IPFS_PATH` is superior.

**Comment by jbenet** [comment]
ok, let's do it. And before the alpha cause this is [one of those things...](https://gist.github.com/cookrn/4015437)
