### ISSUE TITLE
panic on unexpected peer ID

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#398]
secureConn will panic if the peer you are talking to isnt the peer you expect.

How I encountered this:

Create peer A, connect to mars, add and provide a file.
delete peer A's config directory and re initialize, peer A now becomes C
from a second peer (B) request the file that was initially added by A, 
B will now try to connect to 'A' via providers records, but instead connect to C (same ip as original peer A).
handshake assumptions will then fail.

**Comment by jbenet** [comment]
lmk if you can repro this-- it tried quickly with new net code and couldn't.
