### ISSUE TITLE
FindProviders needs a timeout

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#400]
In some 'real world' testing ive been find a large number of goroutines stuck waiting for 'FindProviders' requests to come back, looking into this, There is no timeout set on those requests (sent off into goroutines) so they wait forever for a request from the service. This causes an ugly memory leak of goroutines. What do you guys think an appropriate way to handle this is?

**Comment by jbenet** [comment]
Is this fixed on master? pls reopen if not.
