### ISSUE TITLE
Re-Provide Periodically + After startup

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#414]
when starting up, (and periodically afterwards) nodes should announces all keys that they are providing to the network.

**Comment by jbenet** [comment]
It's important that we make this work-- otherwise basic functions don't work.

**Comment by jbenet** [comment]
Hm, related and probably a good idea too: nodes should persist dht records (best effort, can do it async) as long as they are valid.

**Comment by jbenet** [comment]
this is waiting on #554

**Comment by whyrusleeping** [comment]
addressed as of 2963f48f
