### ISSUE TITLE
Webui Features

### ISSUE THREAD

**Issue by mappum** [jbenet/go-ipfs#415]
This issue is for planning and tracking Webui development. Feature suggestions and feedback belongs here.

## Initial feature planning

[Raw brainstorm output](http://i.imgur.com/6VJN7JK.jpg)

#### Main sections
* **Connections**
  * List of active peer connections
  * Show bandwidth usage
  * Expand entries to show more info about peers
    * Public keys
    * Addresses + geolocation
    * Protocol + agent version
    * Link to bitswap ledger, wantlist
  * Google Earth visualization of connections, traffic
* **Bitswap**
  * Show our wantlist
  * Show peers' wantlists/ledgers
  * Strategy info
  * *go-ipfs*: Requires some additional commands (`ipfs bitswap [ wantlist | ledger | strategy ]`)
* **DHT**
  * Show routing table
  * Hashspace visualization (can show location of PeerIDs+object hashes in a ring)
  * *go-ipfs*: requires a `ipfs dht table` command, and realtime events for the visualization
* **Files** (UnixFS)
  * Show all local files/directories
    * *go-ipfs*: requires a command to list all locally stored files/dirs
  * Resolve hashes for downloading/viewing
  * Show pinned files/directories
* **Objects**
  * Show object links
  * Show object data
  * Link to data as UnixFS file/directory
* **Names**
  * Show/edit IPNS entries
  * *go-ipfs*: Requires a command to list all of our names
* **Config**
  * View/edit config values
* **Logs**
  * Show daemon logs
  * *go-ipfs*: requires a command to download (and maybe stream) logs

#### Other details
* Show when new updates are available, button to download/install them
* Browser mode that keeps a frame with a IPFS address bar (navigates to `/ipfs/hash/foo/bar` paths)
  * Shows smart info about resolving/errors (e.g. `/ipfs/hash/foo` might be valid, but not `/ipfs/hash/foo/bar`)
* Make tables sortable and filterable

**Comment by jbenet** [comment]
Please see #576
