### ISSUE TITLE
ipfs add fails when routing partner goes offline

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#418]
repro:

1. with daemon running, add large file
2. local daemon will provide keys to the network. observe the ID of the peer that receives these keys
3. kill the remote peer
4. **`add` command hangs and fails**

**Comment by jbenet** [comment]
@briantigerchow this is still a problem eh?

**Comment by briantigerchow** [comment]
Don't know for sure. Probably.

Needs a test.

1. Construct two cores and bootstrap them
2. Add/Cat
3. Break the mock net link midway through.
4. Ensure the Add was successful by attempting to Cat locally.

I suppose we want routing, bitswap, blockservice, etc. to respond wisely to the network errors that occur.

**Comment by jbenet** [comment]
Absolutely. That sounds good to me.

**Comment by briantigerchow** [comment]
I'll DRI this one.

**Comment by briantigerchow** [comment]
fixed in #424
