### ISSUE TITLE
ensure bitswap doesn’t rate-limit add operation

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#427]
**context**
When the daemon is running and files are added locally using `ipfs add`, `bitswap.HasBlock` rate limits the operation.

Performing `HasBlock` tasks in the event loop behind a buffered channel (16) was enough to remove the congestion in local tests. I wrote a first draft of a refactor but wasn't pleased with the readability-damage induced by the design. I could take a stab at cleaning it up if you want.

@whyrusleeping You're doing a lot of work in bitswap, so I don't want to get in the way. Let me know how you wanna proceed:

a) @maybebtc proceeds with this issue
b) @whyrusleeping absorbs it into #417 work
c) @maybebtc proceeds and potentially addresses other related things

:information_source: My default stance is to avoid collisions and let you know I'm available to pick up tasks if you're pressed for time.

**Comment by jbenet** [comment]
I'll close this for now. pls reopen if still is problem.
