### ISSUE TITLE
flaky gotests 

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#434]
Of a sample of ~1000 `go test --race` runs, these four tests are responsible for 106 failures.

- [ ] TestConnectCollision
- [ ] TestNotFound
- [ ] TestProvidesAsync
- [ ] TestSendToWantingPeer

https://gist.github.com/maybebtc/e0ab506f4f8341a742da

https://build.protocol-dev.com/job/ipfs_race_tests_on_master/buildTimeTrend

**Comment by jbenet** [comment]
afaict, all these are fixed? would be nice to get another 1000 runs to check ;)
