### ISSUE TITLE
FindProviders regression

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#452]
#440 introduces a bug in the DHT that causes the following test to fail:

1. create network with one bootstrap peer
1. connect a server. connect a client
1. let server add file (client waits for signal to add file)
1. let client cat file

Test fails with output:
```
client: dht: FindProviders Query error: routing: not found routing.go:206
```
The failing test is shown here: https://build.protocol-dev.com/job/ipfs-dockertest/9/console

After reverting the changes, the tests pass. The passing test is shown here: https://build.protocol-dev.com/job/ipfs-dockertest/11/console

The branch with the reverted code is here: https://github.com/jbenet/go-ipfs/tree/revert/dht

@whyrusleeping @jbenet Plan of action?

**Comment by jbenet** [comment]
I think this is fixed. @briantigerchow confirm?
