### ISSUE TITLE
networked add/cat is not functional (master)

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#468]
As mentioned in #466, network functionality is presently (32589ad4bb49fcfbcb36086a46cf1b69465ab252) broken on `master`. If you're looking for a stable version, check out: https://github.com/jbenet/go-ipfs/tree/stable

The bug has been narrowed down to the integration points between bitswap, the dht, and the network.

The failure can be reproduced by running the `make test_docker` integration test. Alternatively, the failure can be repro'd as follows:

1. create a boostrap node B
1. create another node S. Bootstrap S to B.
1. create another node C. Bootstrap C to B.
1. add a file to S.
1. cat the file from C.

There are a few potential ways to move forward. These include, (but aren't limited to):

- [ ] a) temporarily replace the DHT with a centralized routing system #454 
- [ ] b) using the new `net/mocknet` package, exercise the DHT in a DHT/BitSwap integration test to narrow down and find the issue. #461 

For option `a`, since new code must be written on the new network layer, it is important to have high confidence in the foundation. This means it might be wise to address data races recently detected in the CI tests. See: https://gist.github.com/maybebtc/b895a79faf7b97707c45

Option `b` results in a small `go test` case that reproduces the error without the need for process orchestration (ie. docker), but is less useful if option `a` will be pursued.

It's perfectly fine to pursue both options, but there may exist a cheap, effort-minimizing solution that removes the problem quickly and frees up resources to continue regularly-scheduled development.

@jbenet thoughts?

**Comment by jbenet** [comment]
fixed.
