### ISSUE TITLE
Bootstrap Weirdness

### ISSUE THREAD

**Issue by zignig** [jbenet/go-ipfs#472]
With only 1 bootstrap node in config I am still getting 

11:15:36.119 ERROR       core: <peer.ID QmcTRX> bootstrap error: must bootstrap to 3 more nodes, but already connected to all candidates bootstrap.go:90
11:15:36.119 ERROR       core: must bootstrap to 3 more nodes, but already connected to all candidates bootstrap.go:38
11:16:06.119 DEBUG       core: <peer.ID QmcTRX> bootstrapping to 3 more nodes bootstrap.go:66
11:16:06.120 ERROR       core: <peer.ID QmcTRX> bootstrap error: must bootstrap to 3 more nodes, but already connected to all candidates bootstrap.go:90
11:16:06.120 ERROR       core: must bootstrap to 3 more nodes, but already connected to all candidates bootstrap.go:38

**Comment by jbenet** [comment]
@zignig should be fixed in #426. reopen if you see it. thanks!
