### ISSUE TITLE
Sessions in odd state

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#496]
Setup: 

2 nodes:
* celebdil: linux vps in the cloud
* lorien: darwin laptop. bootstraps to celebdil

events:
* started celebdil
* started lorien
* bootstrap worked
* able to cat files in both directions
* big files slow.
* sleep lorien (close laptop). wait 2 hrs
* wake lorien (open laptop). ipfs still running. bootstrap cycle still attempts to run.
* seems like p2p/ maintained the connection open, despite tcp dying. (not torn down)
* cat local objects in lorien worked fine.
* cat local objects in celebdil worked fine
* cat celebdil objects from lorien fails (expected hang).
* celebdil doesnt get anything.
* restart lorien daemon. connects to celebdil.
* lorien attempts cat. still nothing.
* likely that celebdil's connection to lorien was "still open" (not torn down properly either).
* unlikely but possible that celebdil got into a bad state after running for so long.

i'll look at the logs later.

**Comment by whyrusleeping** [comment]
Yeah, cleaning up after dead connections isnt something we do yet. I kinda expect the behaviour you're seeing here. 

my idea of whats going on: the remote sees an 'open' connection to the peer ID is is searching for, and uses it, resulting in a hung connection.

**Comment by whyrusleeping** [comment]
Or maybe, when you dial, it terminates the new connection because you already have one 'open' ?

**Comment by jbenet** [comment]
yeah i think this is lacking garbage collection on the connections
