### ISSUE TITLE
Start using `multihash` tool instead of `shasum`

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#500]
@whyrusleeping said `shasum` is not on all machines.

I recently wrote this go tool: https://github.com/jbenet/go-multihash/tree/master/multihash

```
go get github.com/jbenet/go-multihash/multihash
```

We can use it instead of `shasum`.

It would be good to have some fallback though, to make sure an error in the `multihash` tool doesn't hurt ipfs. Maybe make sure we manually verify the hashes with `shasum` when add them to the code.

**Comment by whyrusleeping** [comment]
relying on git instead of wget would be one fewer dependency (you need git to get ipfs in the first place)

**Comment by jbenet** [comment]
Not sure if this is done on all tests now. let's verify

**Comment by cryptix** [comment]
Can be closed, I think. Afaict, `shasum` is only used by the sharness tests of the vendored go-multihash.

```
[cryptix@higgs ~/go/src/github.com/jbenet/go-ipfs:master] git log -1
commit 11dc94b50c9206ceb42d0ad4b6fc92b58f2c9858
Merge: b4da412 666f457
Author: Juan Batiz-Benet <juan@benet.ai>
Date:   Wed Mar 25 17:42:50 2015 -0700

    Merge pull request #965 from MichaelMure/patch-1
    
    Add a basic command line completion for IPFS
[cryptix@higgs ~/go/src/github.com/jbenet/go-ipfs:master] grep -R shasum .
./Godeps/_workspace/src/github.com/jbenet/go-multihash/multihash/README.md:The `multihash` tool uses `go-multihash` to hash things much like `shasum`.
./Godeps/_workspace/src/github.com/jbenet/go-multihash/test/sharness/lib/test-lib.sh:for hashbin in sha1sum shasum; do
./Godeps/_workspace/src/github.com/jbenet/go-multihash/test/sharness/t0020-sha1.sh:test_expect_success SHASUM "check hash using shasum" '
```

**Comment by chriscool** [comment]
Yeah, I added it to go-multihash and removed it from everywhere else on purpose.
Thanks @whyrusleeping for closing it just now!
