### ISSUE TITLE
Progress Indicator (add/cat)

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#501]
Would be nice to have progress indicators for `ipfs cat` like `scp`:

```
/ipfs/<hash>/<path>                   52%  715MB 567.9KB/s   19:34 ETA
```

Files <1 block are small enough not to need the size estimate (good cause we wouldn't have it). But for files larger, it would be great to know where we're at.

**Comment by mappum** [comment]
What would be outputting that progress indicator? Stdout is already outputting the file contents.

This could work if we had a separate command that outputs the file to disk instead of through stdout (could be called `ipfs get`). That actually makes a lot of sense since `ipfs cat` can't download directories, and get could.

**Comment by mappum** [comment]
Also, I was thinking about the possibility of a progress indicator for `ipfs add` (it would similarly only show it for large files).

**Comment by jbenet** [comment]
> How would we output that progress indicator? Stdout is already outputting the file contents.

Same way curl's does: stderr with lots of terminal redrawing.

> `ipfs get`. That actually makes a lot of sense since `ipfs cat` can't download directories, and get could.

+1 for `ipfs get`. though, maybe we could build the functionality into cat. not sure. cat and get are `unixfs` specific too, at least for the time being.

**Comment by jbenet** [comment]
Poor-man's version: add a `-v` to `ipfs cat` that dumps each objects being read to `stderr`. something like:

```
ipfs cat: reading <hash1> 1/N
ipfs cat: reading <hash2> 2/N
ipfs cat: reading <hash3> 3/N
ipfs cat: reading <hash4> 4/N
```

or something.

**Comment by jbenet** [comment]
This is really important for alpha. It is unacceptable for the user not to know when a major operation is taking place, and how progress is proceeding. `ipfs add` and `ipfs cat` on anything above 1MB is frustrating to use.

**Comment by jbenet** [comment]
we can use this: https://github.com/cheggaaa/pb

**Comment by travisperson** [comment]
I took a bit of a look at this. Curl will give you progress when stdout has been redirected. After a bit of searching there is a package[0] that can determine if a fd is a terminal or not. I've looked a bit into the code for `cat` and the command structure in general and it appears a change would be required. 

Currently commands return a single Reader which is copied to stdout, I'd assume a way for stderr to be returned from commands would be required first.

[0] https://godoc.org/golang.org/x/crypto/ssh/terminal#IsTerminal

**Comment by travisperson** [comment]
Also, missed this:

There is a isTerminal in commands/cli/parse.go

**Comment by whyrusleeping** [comment]
I dont think that can tell if youve redirected to a file though

**Comment by mappum** [comment]
Here's what I'm thinking for the API changes to allow progress bars. Most of the logic can be implemented in `commands.Response`. A `Response#ShowProgressBar(out io.Reader)` function could be added that starts drawing the progress bar if the `Response`'s output is an `io.Reader`, and if a length property has been set.

To set the length, a command will have to set `res.SetOutputLength(n)` in its run function (but this means we will have to switch the API for run functions to get passed a `Response` again). An alternative that requires lest refactoring is to have run functions return a `LengthReader`, which will just be a wrapper around `io.Reader` with an additional `Length` field or function.

This only makes it possible for `cat` though, I'm not yet sure about how to support `add` :/

**Comment by mappum** [comment]
Maybe `add` could do the progress bar drawing inside its marshaler function. The run function could output progress info through a channel, then the marshaler will receive and update then bar when necessary. That's a little janky though, since the marshaler is then writing out to STDERR (but easy to implement and wouldn't require refactoring).

**Comment by jbenet** [comment]
> A `Response#ShowProgressBar(out io.Reader)` function could be added that starts drawing the progress bar if the Response's output is an `io.Reader`, and if a length property has been set.

This isn't a good interface, it's baking in specifics into the cmds lib. The next time we want to show something different we have to modify it too. This should be achievable by just setting a header on the response, and letting implementations interpret the header as they wish (http sets the `Content-Length` and cli client shows a progress bar if it makes sense (note that for `cat` it only makes sense in certain cases, where the output is redirected...) 

That, or a complete side-band io.Reader like `os.Stderr` (not sure what that would mean in HTTP case)

**Comment by danimesq** [comment]
@jbenet or @mappum 
Any progress about progress bar?
Implemented either directly in the Go source or as an external method/workaround.

I would like to have it in `ipfs get` and `ipfs add`.
