### ISSUE TITLE
`ipfs bootstrap {add, rm} -` read from stdin?

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#502]
Would be nice to be able to do:

```
ipfs bootstrap > .bootstrap
ipfs bootstrap add < .bootstrap
```

we can use the usual `-` for stdin:
```
ipfs bootstrap add - < .bootstrap
```

or an option:
```
ipfs bootstrap add --stdin < .bootstrap
```

or that's the mode it goes into if:
- there are no args
- `--default` is not set

**Comment by mappum** [comment]
We already have built-in stdin argument support (`echo "test" | ipfs block put` works), but it reads in the whole stdin as a single argument string. For cases like this, should we treat each line as a separate argument?

**Comment by mappum** [comment]
BTW, instead of turning on stdin with an option, it currently detects if something is being passed in. If so, it appends it to the normal arguments.

**Comment by jbenet** [comment]
Hm, we should probably hand it in as a reader. Some commands will want to process it as a full io reader, and others will want to use a line-delimited entry reader. for the latter, could do something like:

```go
func doSomething(r io.Reader, mapFunc func(line string)) error {
  lr := LineReader(r)
  for {
    l, err := lr.ReadLine()
    if err != nil && err != io.EOF {
      return err
    }

    mapFunc(l)
  }
}
```

others might be more like this:


```Go
func doSomething(r io.Reader, mapFunc func(line string)) error {
  lr := LineReader(r)  
  lines, err := lr.ReadAllLines()
  if err != nil {
    return err
  }

  for _, l := range lines {
    handle(l)
  }
}

func (lr *LineReader) ReadAllLines() ([]string, error) {
  lines := []byte{}
  for {
    l, err := lr.ReadLine()
    if err != nil && err != io.EOF {
      return nil, err
    }
    lines = append(lines, l)
  }
  return lines, nil
}
```

**Comment by jbenet** [comment]
> BTW, instead of turning on stdin with an option, it currently detects if something is being passed in. If so, it appends it to the normal arguments.

Ah, right, great!

**Comment by jbenet** [comment]
@mappum does this work now? can you add a sharness test for it?
