### ISSUE TITLE
Name Resolve Failing

### ISSUE THREAD

**Issue by zignig** [jbenet/go-ipfs#516]
on 5853a25a1c120a4ecae6b11b54877fc69fec95d7

> ipfs name resolve 

2015/01/08 10:39:38 http: panic serving 127.0.0.1:47416: Commands must return a pointer, io.Reader, or channel
goroutine 2511 [running]:
net/http.func·011()
       /usr/local/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x906b20, 0xc208b07ba0)
        /usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/jbenet/go-ipfs/commands.checkType(0x906b20, 0xc208b07b90, 0x0, 0x0, 0x0, 0x0)
        /usr/local/golang/src/github.com/jbenet/go-ipfs/commands/command.go:262 +0x13e
github.com/jbenet/go-ipfs/commands.(*Command).Call(0xef40a0, 0x2b5a7240a418, 0xc2083930e0, 0x0, 0x0)
        /usr/local/golang/src/github.com/jbenet/go-ipfs/commands/command.go:117 +0x68e
github.com/jbenet/go-ipfs/commands/http.Handler.ServeHTTP(0x1, 0xc20800ef40, 0x15, 0xc2080403c0, 0xc6a1a0, 0xc208060240, 0xc20800efa0, 0xef40a0, 0xaeeef0, 0x0, ...)
        /usr/local/golang/src/github.com/jbenet/go-ipfs/commands/http/handler.go:67 +0x377
github.com/jbenet/go-ipfs/commands/http.(*Handler).ServeHTTP(0xc208456910, 0x2aaaaac11ad0, 0xc2080630e0, 0xc20845c000)
        <autogenerated>:2 +0xb5
net/http.(*ServeMux).ServeHTTP(0xc208333800, 0x2aaaaac11ad0, 0xc2080630e0, 0xc20845c000)
        /usr/local/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080434f8, 0x2aaaaac11ad0, 0xc2080630e0, 0xc20845c000)
        /usr/local/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc208d14b00)
        /usr/local/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /usr/local/go/src/pkg/net/http/server.go:1721 +0x313

**Comment by jbenet** [comment]
Sorry for breaking things @zignig, reverted back to 04b938b.

@mappum I restored the `assert-types` branch
