### ISSUE TITLE
Build Failing Windows , fuse issues

### ISSUE THREAD

**Issue by zignig** [jbenet/go-ipfs#517]
build is failing on windows because of fuse ( does not work on windows ), will find the commit.

**Comment by zignig** [comment]
My windows box it at home , I'll track down the fuse/fs ref ( it may need a <BLAH>_windows.go dummy method) when I am back tonight.

**Comment by whyrusleeping** [comment]
I, unfortunately require a windows box for gaming.. So the possibility exists that I could triage this one.

**Comment by jbenet** [comment]
I think this is fixed now

**Comment by cryptix** [comment]
We might want to update the [fuse docs](https://github.com/jbenet/go-ipfs/blob/master/docs/fuse.md) about the `nofuse` tag.

@zignig see #959 for more
