### ISSUE TITLE
ipfs add opening too many files

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#536]
I wanted to test out some of what ipfs could do, so i decided to add the entire go-ipfs directory, recursively. Ipfs wasnt too happy (or rather, my OS wasnt too happy with ipfs)

```
whyrusleeping@alarm ~/g/s/g/j/go-ipfs> ipfs add -r .
Error: open exchange/bitswap/testnet/interface.go: too many open files
```

**Comment by whyrusleeping** [comment]
(in the above text, `exchange/bitswap/testnet/interface.go` is simply the file trying to be added, not where the error is occuring)

**Comment by whyrusleeping** [comment]
This is happening because the cli parser opens file arguments up as it encounters them, recursively.

https://github.com/jbenet/go-ipfs/blob/master/commands/cli/parse.go#L269

**Comment by jbenet** [comment]
@whyrusleeping @mappum this should be done one at a time :/

**Comment by vcunat** [comment]
I'm getting the same error, though maybe for a different reason. I'm running a recent version 9c6ec296e396 with go-1.5. I basically just initialized ipfs, started the daemon and started browsing the webui. Very soon the page stops working; I list daemon output below. I now reproduced this reliably several times.

```
$ ipfs daemon
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.242/tcp/4001
Swarm listening on /ip4/78.128.177.202/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
ERRO[12:26:16:000] too many open files, retrying in %dms0        module=flatfs
ERRO[12:26:16:000] too many open files, retrying in %dms100      module=flatfs
[... many of almost same messages ]
```

**Comment by whyrusleeping** [comment]
@vcunat could I get the output of `ipfs diag sys` on this issue? https://github.com/ipfs/go-ipfs/issues/1939
