### ISSUE TITLE
ipfs ls lists incorrect file size

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#543]
```
whyrusleeping@alarm ~/code> ipfs ls Qmc1GTfmCf4XkSc2ygPRvCAquJv5so7momUiU1zWFbkiSv
Qmb2kSYV4pZa1Jixvgc3PZWjB7kYmav8z2EuA1SSjesUVY 166 blah.go
QmZrKd8vfEK14MXRVdFnPH6R5eWfBc4o72wLsxKVczjuKw 480 dial.go
QmZXbjnjwLWmoYWJZ2stDq2hsvMjMRa8hr4dLvY6Kdwkah 184 main.go
QmeW1FdT1rWpr49NmR1pEycwTZZBQWd2TqMhYiRm4MobJE 4212223 temp
QmdmumAN95uSkFSgnNBQVd6m5gJkwTjEPxEo3mhx21y918 69 test.go
whyrusleeping@alarm ~/code> ls -l temp
total 4132
-rw-r--r-- 1 whyrusleeping whyrusleeping     155 Jan 11 08:36 blah.go
-rw-r--r-- 1 whyrusleeping whyrusleeping     469 Jan 10 04:08 dial.go
-rw-r--r-- 1 whyrusleeping whyrusleeping     173 Jan  8 23:34 main.go
-rwxr-xr-x 1 whyrusleeping whyrusleeping 4211160 Jan  8 23:34 temp*
-rw-r--r-- 1 whyrusleeping whyrusleeping      61 Jan 11 01:01 test.go
```

It appears to be printing to total size of the merkledag object. Maybe thats what we want to do? But personally, i think it should be the actual data size of the file.

**Comment by whyrusleeping** [comment]
The downside of displaying 'actual' filesizes, is that we have to fetch the first block of each entry. which isnt necessarily a bad thing, its just more work to be done.

**Comment by jbenet** [comment]
@whyrusleeping this is correct. it should be displaying the merkledag sizes.

**Comment by travisperson** [comment]
To at least add an explanation, you could print a message at the top of each `ls` stating that file sizes are of the merkledag object and do not represent an accurate file size, as you are listing from ipfs, not your fs. Not the prettiest but it would quickly answer a users questions. After a while people would just start to ignore it and being at the top it isn't too intrusive. Similar to gits status command. And as long as it's a single line or so it can be throw away from output pretty easily with sed/awk/tail if people want to pipe it.

**Comment by whyrusleeping** [comment]
something like:

```
ipfs ls: showing merkledag objects and their respective sizes
```

maybe?

**Comment by jbenet** [comment]
That should be in the help text, not in command output. Command output must be easily scriptable.

—
