### ISSUE TITLE
Webui Readiness

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#576]
The webui is awesome. This issue is here to track close integration with the `go-ipfs` source code, and ensuring that when users install `ipfs`, they get the webui, and it all works out of the box.

- [x] setup build script on webui repo to make a release bundle
- [ ] setup script to add webui hash to `go-ipfs`
- [ ] add the diag-net viewer to webui :D
- [ ] ensure all the alpha features are there and work properly. this means:
  - [ ] create a checklist for all features (@mappum)
  - [ ] walk through them and test them out (@whyrusleeping, @jbenet, @briantigerchow)
  - [ ] fix any issues / suggestions

**Comment by mappum** [comment]
Here is the latest webui: [QmNdsUHYpvNpYkXJs4BYJymET3YwAGRYPTy5v6J29qvDF4
](http://localhost:5001/ipfs/QmNdsUHYpvNpYkXJs4BYJymET3YwAGRYPTy5v6J29qvDF4)

**Feature Checklist**
* [ ] Home
  * View based on `ipfs id` output
  * Geolocation based on current swarm addresses
* [ ] Connections
  * List of peers, based on output of `ipfs swarm peers`
  * Globe, showing a point for each peer
  * Peers in list expand to show detailed info (based on `ipfs id <peerid>`)
  * List updates without refreshing (try `ipfs swarm connect <foo>` and see it show up in the list)
* [ ] Files
  * Add files with "Add a file" button
  * Pinned files show up in list (based on `ipfs pin ls` output)
  * Other local blocks show up in list (based on `ipfs pin ls --type=recursive` output)
  * Lists update without refreshing (try `ipfs pin add <foo>` in your CLI while the webui is open)
* [ ] DAG
  * List of links in object, can be followed to explore the DAG structure
  * Display of data in object (as text)
  * "Raw" link loads data for that object from gateway
* [ ] Config
  * Shows contents of current config file (`ipfs config show`)
  * Shows JSON errors when editor contains invalid JSON
  * Saves new contents when "Save" button is pressed
* [ ] Log
  * Shows realtime event log output - (not pretty, I heard @travisperson made a cool viewer that we could use?)

**Comment by jbenet** [comment]
Btw, here's some feedback of when I sent this to a designer. probably worth holding off until the design returns, but: http://gateway.ipfs.io/ipfs/QmWutsjiuUYZ73KwXkbVFzBU7LVTDD4AExpzbJ1MZjYURk/mdown#/ipfs/QmbYW2hQ987H4RwnBgwx47UqNVi9eKob73FyC2qKeM7Sda/uinotes.md

**Comment by whyrusleeping** [comment]
For the logs, lets definetly use @travisperson's viewer, we have a hackathon this weekend where im sure he would love to finish working on it. Right Travis?? :smile:

**Comment by dborzov** [comment]
How do you envision "*setup script to add webui hash to go-ipfs*"? Could it be something like:

* a harcoded hash for the default webUI version coming with each IPFS release
* include support for an IPFS config option "customWebUI", which allows for overwriting the default WebUI version. If the custom version is not resolved, the default version is shown
* `go generate`-based macros to update the hardcoded webUI hash (or maybe a shell script looking up the latest release at `protocol/web-ui` repo)
