### ISSUE TITLE
Gateway Setup

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#577]
cc @briantigerchow @mappum
We have the HTTP gateway working, you can see IPFS in IPFS over IPFS/HTTP at: http://ipfs.benet.ai:8080/ipfs/QmckFjF9oQsnXB2uCAT5vuDnVUjBrjYsApjDJ2CtTAWQsF/

We need to make the gateway work. the plan is the following:
- [x] make a gateway distribution for us to run (this can be just a config (ansible?) or a separate binary)
  - [x] gc periodically, we dont want to store things long term there, only cache them. (we can start weekly, and move down to daily, etc). Bonus points for identifying hot items and caching those.
  - [ ] ipfs blacklist -- we need a way to provide _our_ ipfs gateways a blacklist of things not to serve.  we need to be ready for this, as it _will_ come, and I dont want malicious use of _our_ infra interfering with our alpha launch.
- [x] setup gateway network to serve many gateways. these:
  - [x] N machines, each running nginx and ipfs
  - [x] ~~each node runs `K~5` ipfs nodes~~
  - [x] nginx proxy pass points to all other N ipfs nodes too, to failover
  - [x] monitor to automatically restart ipfs and nginx
  - [x] dns A records on gateway.ipfs.io to point to N nodes
  - [x] dns A records on ipfs.io point to N nodes once it's been thoroughly tested

[1] @mappum observed that dns resolving creates a problem if a gateway goes down. users would only fail over to another once their dns entry expires. we can anycast once the gateways _prove robust_.

**Comment by whyrusleeping** [comment]
> ipfs blacklist
I can implement a blacklist into bitswap, should be fairly trivial to write, I can also add a command to modify the list.

Also, I would really like if the gateway could serve ipns, that should be a relatively simple addition.
