### ISSUE TITLE
Implement UDP as a swarm protocol

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#58]
Having UDP as a protocol for swarm to use will make ipfs MUCH more flexible. 

Some considerations will need to be taken for packet loss though, in some cases lost packets are not okay. Implementing a basic packet-wise ACK system might be useful.

**Comment by jbenet** [comment]
Update: #488 revealed that h2so5/utp (old "working" commit) was breaking as a transport. #490 removed it. We will have to get another udp reliable transport for nat:
- utp - https://github.com/h2so5/utp is not yet ready
- udt - https://github.com/jbenet/go-udtwrapper does not have required assembly for arm.
- sctp - maybe i should wrap sctp. hopefully it doesn't have assembly. wont be quick though.

---

@oxtoacart are you guys using go-udtwrapper*? (something else for udp reliability in go?) @whyrusleeping had trouble running it in his ARM chromebook, we determined it was some missing ARM assembly in the c++ udt lib. I haven't looked into this-- will soon-- but just thought you should know.

**Comment by oxtoacart** [comment]
@jbenet Thanks for the heads up!  We're not actually using go-udtwrapper yet.  First we have to release a build that includes go-natty and collects some stats on how well nat-traversal is working.  Actually proxying traffic over UDP will hopefully follow not too long thereafter.

**Comment by jbenet** [comment]
@oxtoacart sounds good. I'm about to work on bundling go-natty into go-ipfs (at some point soon we should discuss making `natty` strip out the relevant c++ from webrtc and either building a tiny binary, or link it in using cgo. currently `natty` adds ~10MB (or is it 40+MB if you bundle multiple archs together?))

**Comment by oxtoacart** [comment]
@jbenet The natty version for each architecture is compiled into the go build for that architecture, so you're looking at just one natty executable as overhead.

**Comment by oxtoacart** [comment]
BTW, I know that @atavism wants to work on decreasing the size of the binary, but he has his plate full with other stuff at the moment.

**Comment by jbenet** [comment]
Ah okay, thanks! And no worries, this is lower priority stuff :)

**Comment by oxtoacart** [comment]
@jbenet Thank you!  Hope you had a nice holiday season.

**Comment by jbenet** [comment]
thanks! same to you all! btw, feel free to hang out with us in #ipfs

**Comment by whyrusleeping** [comment]
we have UDT that *works* just needs to be wired in, I think this can be closed now

**Comment by jbenet** [comment]
Update on uTP. anacrolix wrote to the go-nuts mailing list:

> I ended up writing https://github.com/anacrolix/utp for this. I found h2so5/utp to be unstable and hard to work with. anacrolix/utp is at least very stable, and has been used in production for 8 months now. Its performance could be better, and some things in the spec could be clarified, but if you want to use uTP, this will get the job done.
> From https://groups.google.com/d/msg/golang-nuts/Co8vQ0KkrLU/qeTcEgHvR9oJ

https://github.com/anacrolix/utp/

perhaps we should try it out :) 

i would be more comfortable if we had a large cross-internet test case.

**Comment by xaionaro** [comment]
Well:
* go-utp-transport -- doesn't work (doesn't compile)
* go-udp-transport -- not implemented
* go-libp2p-quic-transport -- doesn't work with ED25519. And I think I fixed it, but now it tells me something like "Dial: backoff".

But the ticket is closed :). Can we reopen the ticket?

Reference: https://github.com/libp2p?utf8=%E2%9C%93&q=transport&type=&language=go

**Comment by Stebalien** [comment]
This issue has a _lot_ of outdated information. I've created a new UDP meta issue: https://github.com/ipfs/go-ipfs/issues/6481.
