### ISSUE TITLE
de-duplicate blockservice providing

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#609]
When a file is added twice in quick succession, blocks are queued up to be provided twice.

```
ipfs add large_file # provides to network
ipfs add large_file # provides to network again (even if previous keys are still in the queue)
```

It may make sense to allow re-providing if the RPCs have already gone out. Doesn't make sense at all when the blocks are still waiting to go out the first time.

**Comment by jbenet** [comment]
:+1:
