### ISSUE TITLE
Public REST interface to add nodes

### ISSUE THREAD

**Issue by mildred** [jbenet/go-ipfs#611]
Hello, I have the need of a REST interface on the public server (not the API server listening on localhost only). The project idea is to create a web application to create/update websites. It needs a way to save a page to IPFS.

I was that there was already a POST request handler (that is not connected) in `cmd/ipfs/gatewayHandler.go` function `postHandler` introduced in commit 897e0f869f9ec6300a5615a061cdee26402bd654

I started developing on a new API, mostly to try things around. But I want to start a discussion about this as well. We would need several things from the API, and I think of the following routes:

1. a way to add a file not knowing its hash
2. a way to add a file in a directory structure. Duplicating the directory structure up to the root hash
3. a way to remove a link from a directory, duplicating the directory structure
4. a way to add an empty directory
5. a way to add an empty directory to a structure, duplicating the structure

This way, we can have a pseudo-mutable file hierarchy on IPFS. Each time a modification is made, a new root hash is computed. The idea is that when IPNS will be ready, the web client will be able to take this new hash and sign it using a client-side private key and update the IPNS record with.

I'm now thinking of these routes for the previous use-cases:

1. `POST /ipfs/`: the response should redirect 303 to the created object
2. `PUT /ipfs/HASH/path/file`: duplicate the directory structure and add the uploaded file to the new structure. Redirect 303 to the new directory structure `/ipfs/HASH2/path/file`. If `/ipfs/HASH/path` does not exists, it is created as an empty directory
3. `DELETE /ipfs/HASH/path/file` removes the link `file` from `/ipfs/HASH/path` in a duplicated directory structure. Redirect 303 to the new directory structure `/ipfs/HASH2/path/`.
4. `PUT /ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn/`: the hash of the empty directory.
5. `PUT /ipfs/HASH/path/dir/`: Same as (2) but with no request body and terminated by a `/`.

I don't know if we should use PUT or POST for requests 2 and 5. PUT is supposed to apply on the definitive URI and we can't because the HASH is forced to change. But that's the same for DELETE. PUT has another advantage: it is idempotent. The request can be repeated any number of time safely.

**Comment by zignig** [comment]
awesome plan, a good articulation of what i've been thinking. :+1:

**Comment by mildred** [comment]
Looking at the [HTTP 1.1 RFC](https://tools.ietf.org/html/rfc2616#section-14.30) about the Location field, I think it is better to not to reply with a 303 (See other) status code but with 201 (Created):

    The Location response-header field is used to redirect the recipient
    to a location other than the Request-URI for completion of the
    request or identification of a new resource. For 201 (Created)
    responses, the Location is that of the new resource which was created
    by the request. For 3xx responses, the location SHOULD indicate the
    server's preferred URI for automatic redirection to the resource. The
    field value consists of a single absolute URI.

**Comment by jbenet** [comment]
@mildred thanks for articulating it so well! Agreed we need this. I think the 5 routes + methods you mention is a great starting point. On `PUT` vs `POST`, we could actually just use both. There's many http clients out there that are limited in which method they use. @mappum thoughts?

Also, in mounted-ipfs, we will have a set of special files (plan9 or /dev style) that helps with this sort of thing. We haven't outline this set yet, but thinking something like:

```sh
> echo "hello" >/ipfs/_/add
> cat /ipfs/_/added
QmUJPTFZnR2CPGAzmfdYPghgrFtYFB6pf1BqMvqfiPDam8
> cat /ipfs/QmUJPTFZnR2CPGAzmfdYPghgrFtYFB6pf1BqMvqfiPDam8
hello

_ is a placeholder for something like {ipfs, api, special, ...}
```


cc @whyrusleeping -- this is actually highly related to the semantics for writable mounted-ipns. and it may be that we could adopt writable mounted-ipfs semtantics (if we can `chdir` for the user, like an HTTP redirect)

**Comment by mildred** [comment]
I agree that the gateway interface and the mounted filesystem should have the same file hierarchy. This is a sane thing to do.

About the interface you just suggested (the add file and the added file) I think there is a problem with that. There will be a race condition between the moment the file is added by writing to `add` and the moment its hash will be read using `added`. We should perhaps use a file socket instead where we would write the file on the same file descriptor than reading the resulting hash.

But I think we should track this in a separate issue

**Comment by whyrusleeping** [comment]
There isnt necessarily a race condition in those semantics. If implemented properly, it would be fine. running `cat /ipfs/_/added` will invoke a fuse handler, where we can check for 'in progress' adds and wait for them to resolve if need be, and ensure synchronization from there.
