### ISSUE TITLE
Large number of active peer queues building up

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#627]
I left my daemon running overnight, and decided to kill it this morning, When i did i was presented with a barrage of 'PeerQueue closing' messages, which implies to me that there were at least that many active PeerQueues. It seems they arent being properly closed during normal operation.

Relevant log output: https://gist.github.com/whyrusleeping/28506a578948cfec7f2e

**Comment by jbenet** [comment]
> When i did i was presented with a barrage of 'PeerQueue closing' messages, which implies to me that there were at least that many active PeerQueues. It seems they arent being properly closed during normal operation.

Ohhh! interesting. yeah good point.
