### ISSUE TITLE
CLI helptext obscures errors

### ISSUE THREAD

**Issue by mappum** [jbenet/go-ipfs#630]
Helptext output of commands that return a client error is pretty big, and obscures the error (making it harder for the user to see).

**Comment by lgarron** [comment]
The current length of the help string is a bit intimidating.
If I'm using a tool for the first time and the output fits on a screen, it's friendly. More than one page, and it's *much* more likely to turn me away.

I’d advocate for a shorter version (≤20 lines) that also tells you to run `ipfs help` for a larger list of commands.
