### ISSUE TITLE
File MetaData object

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#661]
- [ ] MIME type
- [ ] add it to unixfs
- [ ] make webui return it.
- [ ] make webui add it

**Comment by whyrusleeping** [comment]
I think i can tackle this one, since im the most familiar with unixfs

**Comment by whyrusleeping** [comment]
Im thinking something like:
```
{
    "Name":"filename.mp3",
    "Data" : "QmHashOfContent",
    "Mime" : "blah blah mime type",
}
```

Very basic, and gets the job done.

**Comment by whyrusleeping** [comment]
An example of what could go in the links of the metadata object could be 'prefetch nodes' that could be fetched concurrently with the root block of the object being described, that way data could arrive at roughly the same time that we start to request it.

**Comment by jbenet** [comment]
what's the `QmHashOfContent`? the root? (it will already be in the links).

I'm wondering, maybe we want to make the mimetype a link to a mime type definition

**Comment by whyrusleeping** [comment]
I guess it would make sense to have the root hash as a link. (as well as the filename) We could make the mimetype be a separate linked object, but thats an extra resolution that has to happen. On the other side though, those are very likely to be cached, so it wouldnt matter much.

**Comment by jbenet** [comment]
yeah. maybe we can even ship the most common ones along some set of "likely to be in every node" content.

**Comment by whyrusleeping** [comment]
Well, for common mime types we could use a 'plaintext multihash', something like `QmJSON` or something (obviously not Qm, but a different tag)

**Comment by jbenet** [comment]
Yeah i was thinking that too--- the "identity" "hash". it may introduce a lot of complexity atm so we could punt.

**Comment by whyrusleeping** [comment]
Yeah, im fine with punting it for now, but i dont want to forget about it. Could be really useful!
