### ISSUE TITLE
key + path types

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#664]

**Comment by whyrusleeping** [comment]
For the path type, im thinking of having the following interfaces:

```
type Path interface{
    String()
    Segments() []string
}

func NewPathFromString(s string) Path {...}
```

**Comment by briantigerchow** [comment]
To ground this discussion, this is the particular code snippet that was causing issues for our users:

```Go
func deriveChatId(peerId peer.ID) (ChatId, error) {
	hasher := sha256.New()
	hasher.Write([]byte("/ipfs-chat/"))
	hasher.Write([]byte(peerId))

	chatId := hasher.Sum(nil)

	mbuf, err := multihash.Encode(chatId, multihash.SHA2_256)
	if err != nil {
		return ChatId(0), err
	}

	chatIdString := ChatId(base58.Encode(mbuf))

	return chatIdString, nil
}
```

https://github.com/ali01/ipfs-chat/blob/master/main.go#L116

**Comment by briantigerchow** [comment]
This issue is also about the key confusion decscribed in https://github.com/jbenet/go-ipfs/issues/664#issuecomment-71786387

**Comment by whyrusleeping** [comment]
@briantigerchow could you elaborate a little on what the confusion is?

**Comment by jbenet** [comment]
@whyrusleeping the confusion is that for users first approaching the codebase it's not obvious what a Key is or when a `string` is the b58 encoded or the raw string. We should use types to designate this.

How about:

```go
```

**Comment by jbenet** [comment]
I want to play with a few options. Will ponder this and change it soon, but removing from alpha milestone. The _right_ interface is more important than rushing the choice.

**Comment by whyrusleeping** [comment]
I really want to avoid ever writing `string(x)` in my code. Casts in go almost always cause headaches because youre throwing away type safety.
