### ISSUE TITLE
Ipfs no longer shuts down properly

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#682]
I dont know if this has been filed already (if so, just close this one) but killing ipfs with SIGINT no longer succeeds. This should be alpha priority.

**Comment by briantigerchow** [comment]
I've found it helpful to include a `Debug` log statement in `Close() error` methods of large components. Makes it easy to see when things shut down as they should.

**Comment by whyrusleeping** [comment]
It appears that `dialAddrs` in the swarm doesnt respect the context as well as it should, and even farther down, `rawConnDial` doesnt really use the context, but just sets a timeout. This might be part of the issue, im still investigating.

**Comment by whyrusleeping** [comment]
looks like i noticed this before in #650

**Comment by whyrusleeping** [comment]
I beleive #690 is related as well.

**Comment by whyrusleeping** [comment]
More experiment notes: If i leave my daemon on for a while, and disconnect my internet connection, the daemon appears to close down properly.

**Comment by jbenet** [comment]
i've observed the same. it's related to network connections. probably
contexts not cancelling properly.

**Comment by whyrusleeping** [comment]
The next time anyone encounters the daemon not quitting, could you wait up to one minute? Im thinking that it might be waiting for dial calls to timeout, if thats the case, the daemon should exit once the timeout triggers and we know where to direct our debugging efforts

**Comment by whyrusleeping** [comment]
Just confirmed that the daemon will shutdown at some point after the kill signal is sent, < 30s in my cases.

**Comment by briantigerchow** [comment]
I found it useful to add log statements in the Close() methods of sub-systems to see the order in which they shutdown.
