### ISSUE TITLE
Daemon Freezes and stops responding to requests.

### ISSUE THREAD

**Issue by travisperson** [jbenet/go-ipfs#690]
After a while I'll notice my gateway will start to freeze and throw 500 errors, to fix this I usually have to go in and reboot the daemon. The last time this happened I crapped the panic and my systems open files.

**Log**
http://gateway.ipfs.io/ipfs/QmTEeDfma5Q4H9AzhNoHmHF7QjsHeLMKW7uttmnHCGuPMS

**Open file output**
http://gateway.ipfs.io/ipfs/QmcYPWFzgC7C5ojC3Am21gNqqStCx7zmQpfvJKFphZmrNx

*The above are pinned on http://ipfs.travisperson.com:8080/ if they don't resolve*
![image](https://cloud.githubusercontent.com/assets/165274/5965174/ea0fc2d4-a7ae-11e4-8585-f485d325246d.png)

**Comment by whyrusleeping** [comment]
that definetly is our file explosion error.... I have no idea why we see so many leveldb fds. Maybe i misunderstand how lsof works
