### ISSUE TITLE
Add/Cat interface

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#696]
In #664 `coreunix.Cat` now takes a path. It was nice when `Cat` and `Add` were symmetric. Maybe make `Add` return a path is the right thing to do? cc @whyrusleeping  @briantigerchow

**Comment by whyrusleeping** [comment]
Add could return a path, but it just contains a hash... im fine with it. But its halfway misleading...

**Comment by briantigerchow** [comment]
At this stage, probably want to involve people unfamiliar with the API.

**Comment by whyrusleeping** [comment]
@travisperson how user friendly do you think `coreunix.Cat` and `Add` are?

**Comment by briantigerchow** [comment]
Got bit by the conversion.

:bug: :beetle: 
```Go
175             if _, err := coreunix.Cat(n, path.Path(k)); err != nil {
```

reveals this in debug mode:
```
07:08:17.328 DEBUG       path: Resolve: ' �x{��+YǄP�= �36
                                                         C�,w(���5a resolver.go:24
07:08:17.328 DEBUG       path: given path element is not a base58 string.
 resolver.go:39
```

With the new signature, users must perform multiple conversions to satisfy the function. The UX has just taken steps backward.

```Go
175             if _, err := coreunix.Cat(n, path.Path(k.String())); err != nil {
```

**Comment by whyrusleeping** [comment]
I agree with this. I think Cat should perform a set of checks on its input, make sure it contains a base58 encoded hash somewhere, if the user passes in a key, convert it appropriately, etc. I think path should also have `FromString` and `FromKey` constructors to aid in useablility

**Comment by whyrusleeping** [comment]
I addressed this in #702

**Comment by Dentrax** [comment]
I think `coreunix.Cat` is removed at the `master` branch. What's the alternative way to do `cat()` in current version? @whyrusleeping @btc

**Comment by Stebalien** [comment]
This issue is _quite_ old. Please ask on https://discuss.ipfs.io and provide some more context.
