### ISSUE TITLE
API and gateway return differences 

### ISSUE THREAD

**Issue by zignig** [jbenet/go-ipfs#705]
found a bug between the api and the gateway

with an API call 

 curl "http://localhost:5001/api/v0/cat?arg=QmWBz92zdFMTPntMG2rUoDfENFNL7n1etJZXQqTj27A3fv/sector/00"

gives 

curl: (18) transfer closed with 11 bytes remaining to read

 curl "http://localhost/ipfs/QmWBz92zdFMTPntMG2rUoDfENFNL7n1etJZXQqTj27A3fv/sector/00"

returns file with no errors. 

I suspect the progress bar

**Comment by mappum** [comment]
Hm, it appears the `Content-Length` header is being set incorrectly in cat. It might be coming from the seeking code (that's how the length is getting measured).

**Comment by jbenet** [comment]
the (logical) length of unixfs likely to be different (smaller or larger) than the cumulative length reported in merkledag links. cat uses the merkledag links: 

```go
func cat(node *core.IpfsNode, paths []string) ([]io.Reader, uint64, error) {
	readers := make([]io.Reader, 0, len(paths))
	length := uint64(0)
	for _, fpath := range paths {
		dagnode, err := node.Resolver.ResolvePath(path.Path(fpath))
		if err != nil {
			return nil, 0, err
		}

		nodeLength, err := dagnode.Size()
		if err != nil {
			return nil, 0, err
		}
		length += nodeLength

		read, err := uio.NewDagReader(node.Context(), dagnode, node.DAG)
		if err != nil {
			return nil, 0, err
		}
		readers = append(readers, read)
	}
	return readers, length, nil
}
```

**Comment by jbenet** [comment]
@zignig  check out https://github.com/jbenet/go-ipfs/pull/712 -- it should've addressed this. confirm?

**Comment by zignig** [comment]
Confirmed working with cohort , good for merge

**Comment by whyrusleeping** [comment]
@zignig, im assuming you didnt mean to reopen this.

**Comment by zignig** [comment]
I closed it before it was merged, so I repoened. 

but thanks for fixing and closing!
