### ISSUE TITLE
fd leak

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#706]
We're leaking fds (in linux only i think?). It may be related to our use of `reuseport`. Though leveldb is a bit suspect too (must make sure we close the queries).

**Comment by jbenet** [comment]
Related to #690

**Comment by whyrusleeping** [comment]
This is the biggest issue im running into now. All the machines i have will eventually hit a limit and crash within a day or two. @zignig and @travisperson both have good logs showing massive amounts of open file descriptors. Im going to assign this one to alpha priority.
