### ISSUE TITLE
MIME type on gateways?

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#737]
.mov's still get downloaded for me

**Comment by whyrusleeping** [comment]
We had automatic MIME detection, but it appears to have been removed in d338a81ec in favor of `http.ServeContent` which claims to automatically detect content type.

**Comment by travisperson** [comment]
The [mime package](http://golang.org/src/mime/type.go?s=299:313#L16) only comes with 9 simple mime types.

Add more is pretty simple, pulling a list from apache or nginx might be an option.

Apache
http://svn.apache.org/viewvc/httpd/httpd/branches/2.2.x/docs/conf/mime.types?view=markup

Nginx
https://github.com/nginx/nginx/blob/master/conf/mime.types

**Comment by jbenet** [comment]
thoughts @mappum ?

**Comment by mappum** [comment]
The type detection is still there, provided automatically in the ['http.ServeContent()' function](http://golang.org/pkg/net/http/#ServeContent). Now it also falls back to MIME-sniffing the data to detect the type.

**Comment by mappum** [comment]
I'm not sure why the MOV isn't streaming, could it be a non-streamable movie file?

**Comment by whyrusleeping** [comment]
@mappum look at @travisperson's comment.

**Comment by mappum** [comment]
>@mappum look at @travisperson's comment.

Oops, I missed that. Interesting, maybe we should make a PR to golang to add those. (But until then we can use those larger lists ourselves).

**Comment by jbenet** [comment]
yeah, let's use the larger list

**Comment by whyrusleeping** [comment]
@travisperson is this fixed?

**Comment by jbenet** [comment]
@travisperson reopen if not
