### ISSUE TITLE
peer short tags are too short

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#780]
The shortened peer strings `<QmWhyr>` dont quite show enough of my peer ID's for me to tell which of the nodes im connected to. What do you think about skipping the first two letters (`Qm`) since theyre going to be the same across all peer IDs.

**Comment by techfreek** [comment]
I'd like to take this on, however, I haven't seen the shortened peer strings. could you give me an example of a command that lists shortened peer strings?

**Comment by jbenet** [comment]
>  What do you think about skipping the first two letters...

sgtm :+1: 

> could you give me an example of a command that lists shortened peer strings?

this is mostly for logs and not exposed to users. though i think if you run `ipfs dht query -v <hash>` you'll see them. the relevant code is inside `peer/` pkg somewhere.

**Comment by techfreek** [comment]
@jbenet || @whyrusleeping, if I skip the first 2 characters, should it remain 6 characters long? Or should I bump it to 8 or something like that?

**Comment by whyrusleeping** [comment]
If you skip the first two characters, keeping it at 6 characters seems fine to me.

**Comment by jbenet** [comment]
btw, i just remembered that `Qm` will only be the same for `sha256` peerIDs. our use of the shortened peerid is mostly for debugging anyway, so this may be ok. we can always revert back and bump to 8 chars if we have reason to.
