### ISSUE TITLE
curl POST-ing to gateway strips new lines.

### ISSUE THREAD

**Issue by compleatang** [jbenet/go-ipfs#786]
File I'm trying to POST: https://gist.github.com/compleatang/87603d14f00b2f35c8b8

Command I'm using to POST: `curl --ssl-reqd -ksiX POST -d @ipfs.plugin.zsh https://ipfs.erisbootstrap.sexy/ipfs/`

^ url resolves to the gateway port not the api port.

Result of POST: https://ipfs.erisbootstrap.sexy/ipfs/QmdWxginZJ31kZ1aQUamtKymEkhuikpxbpoLpcTMb6Yp1F

As you can see the new lines have been stripped. It must be something about how the gateway is reading from vanilla curl command.

**Comment by whyrusleeping** [comment]
Instead of `-d` you should use `--data-binary` This is a curl issue.

If this doesnt work out, please reopen the issue.
