### ISSUE TITLE
IPFS 'ls' should show which files are directories

### ISSUE THREAD

**Issue by travisperson** [jbenet/go-ipfs#799]
I was watching the alpha video and noticed something that I think would be really neat.

![screen shot 2015-02-20 at 4 05 08 pm](https://cloud.githubusercontent.com/assets/165274/6311620/5363696c-b91a-11e4-9301-345ae68ac3a5.png)

In the `ls` command for the os, it shows folder with a trailing '/'. Would be nice to see with `ipfs ls` what objects are folders as well.

**Comment by dborzov** [comment]
I would also fix table aligning so that filenames would make a proper "column" for `ipfs ls`.

 I am volunteering to work on this. I can reuse things from my side project [lsp](https://github.com/dborzov/lsp) which is about `ls` command with flashier colors

**Comment by cryptix** [comment]
[tabwriter](http://golang.org/pkg/text/tabwriter/) should take care of the alignment quite easily.

:+1: on the trailing `/` for directories.

**Comment by whyrusleeping** [comment]
Agreed. The only weird thing is that you can `ls` a file to see the blocks in it.

**Comment by whyrusleeping** [comment]
fixed as of #833
