### ISSUE TITLE
ipfs object put should accept stdin

### ISSUE THREAD

**Issue by jbenet** [jbenet/go-ipfs#811]
maybe:
```
ipfs object put - json
```

or move the encoding to a flag and default to json.

**Comment by jbenet** [comment]
#810

**Comment by cryptix** [comment]
Turn's out: there are no sharness test for all the 'ipfs object' commands and the `--enc` flag is broken.:

**Comment by jbenet** [comment]
the `object put` cmd takes the encoding as arg -- i dont remember/know why (@mappum ?) 

```
> ipfs object put --help

    ipfs object put <data> <encoding> - Stores input as a DAG object, outputs its key

ARGUMENTS:

    <data>     - Data to be stored as a DAG object
    <encoding> - Encoding type of <data>, either "protobuf" or "json"
```

so

```
ipfs object put test.json json 
```

**Comment by cryptix** [comment]
aaah - yeah.. that works much better.

**Comment by cryptix** [comment]
#882 is merged so i'll close this one.
