### ISSUE TITLE
localhost:5001/webui/ should work too

### ISSUE THREAD

**Issue by bussiere** [jbenet/go-ipfs#812]
I thinks that i ve done everything right , like launching daemon & co 

But i still don t have the webui interface :+1: 
Screenshot
http://gateway.ipfs.io/ipfs/QmTXMSk9Qe6to2MdHjUAFAyXMfPf4pgkRh65stf6yawQGo

Regards & thanks

**Comment by jbenet** [comment]
@bussiere can you try: http://localhost:5001/webui ? it may be a matter of the trailing slash

**Comment by bussiere** [comment]
yeah it works

**Comment by jbenet** [comment]
thanks! I'll keep this open as we should fix this-- both should work :)

**Comment by BrendanBenshoof** [comment]
Bug is fixed in pull #823

**Comment by Flora258** [comment]
I can't connect to localhost:5001 using the link provided. Does it matter that I'm using Edge?
