### ISSUE TITLE
Webui needs to be updated

### ISSUE THREAD

**Issue by travisperson** [jbenet/go-ipfs#818]
In light of #810, the webui needs to be updated.

**Comment by jbenet** [comment]
@travisperson yep-- want to publish an update? it involves:

- [ ] update the hash in corehttp
- [ ] keep the old hash in the list
- [ ] ensure we pin the next one (i can do this if it's posted here)

**Comment by davidhampgonsalves** [comment]
I updated webui in corehttp to the current QmRjkUt5A3UHjTm5uG9yZG1bRxCv4cveviQHeVTzkpXTFt
https://github.com/jbenet/go-ipfs/pull/824

**Comment by jbenet** [comment]
already updated
