### ISSUE TITLE
contexts: always call returned cancelFunc

### ISSUE THREAD

**Issue by cryptix** [jbenet/go-ipfs#822]
Hi,

according to [this](https://go-review.googlesource.com/#/c/5022/) upstream change, we can't ignore the returned cancelFunc of a context otherweise cleanup of goroutines blocking on `ctx.Done()` can't happend. 

I found at one such case in [routing/dht/records.go](https://github.com/jbenet/go-ipfs/blob/cb6d161b05e7d073ac96357dde2917b52b4c27a5/routing/dht/records.go#L30) and started a branch ([dontIgnoreCancelFuncs](https://github.com/jbenet/go-ipfs/tree/dontIgnoreCancelFuncs)) with a fix but wanted to wait with a PR until we are sure there arn't more easy cases lying around.

**Comment by whyrusleeping** [comment]
Is this the case even if the parent context cancels? The only time ive thrown away cancel funcs is if im confident my parent will cancel for me

**Comment by jbenet** [comment]
that's a bit error prone-- if others change the code above you it will break things. probably safer to cancel always.

**Comment by jbenet** [comment]
- [ ] https://github.com/jbenet/go-ipfs/pull/860/files#r25924773

**Comment by cryptix** [comment]
> The returned context's Done channel is closed when the returned cancel function is called or when the parent context's Done channel is closed, whichever happens first. - [godoc](https://godoc.org/golang.org/x/net/context#WithCancel)

so @whyrusleeping's assumptions holds but I agree with @jbenet that it is error prone. If the parent changes to a non-canceling one for instance.

**Comment by cryptix** [comment]
pushed fix for the ones in PR860 that @jbenet linked to.

here is a list of outstanding ones
```
[cryptix@higgs ~/go/src/github.com/jbenet/go-ipfs] grep -R '_ := context.WithTimeout' | grep -v Godeps | grep -v _test
p2p/net/swarm/swarm_dial.go:            ctxT, _ := context.WithTimeout(ctx, s.dialT)
merkledag/merkledag.go: ctx, _ := context.WithTimeout(context.TODO(), time.Minute)
diagnostics/diag.go:    ctx, _ := context.WithTimeout(context.TODO(), timeout)
pin/pin.go:     ctx, _ := context.WithTimeout(context.Background(), time.Second*60)
exchange/bitswap/bitswap.go:                    child, _ := context.WithTimeout(ctx, providerRequestTimeout)
exchange/bitswap/bitswap.go:            hasBlockCtx, _ := context.WithTimeout(ctx, hasBlockTimeout)
routing/dht/dht.go:                             ctx, _ := context.WithTimeout(dht.Context(), time.Second*5)
unixfs/tar/reader.go:           ctx, _ := context.WithTimeout(context.TODO(), time.Second*60)
core/corenet/net.go:    ctx, _ := context.WithTimeout(nd.Context(), time.Second*30)
core/commands/ping.go:                  ctx, _ := context.WithTimeout(ctx, kPingTimeout)
core/commands/ping.go:                  ctx, _ := context.WithTimeout(ctx, kPingTimeout)
core/commands/id.go:            ctx, _ := context.WithTimeout(context.TODO(), time.Second*5)
(12)

[cryptix@higgs ~/go/src/github.com/jbenet/go-ipfs] grep -R '_ := context.WithDeadline' | grep -v Godeps 
grep -v _test
namesys/publisher.go:   timectx, _ := context.WithDeadline(ctx, time.Now().Add(time.Second*10))
(1)

[cryptix@higgs ~/go/src/github.com/jbenet/go-ipfs] grep -R '_ := context.WithCancel' | grep -v Godeps | grep -v _test
(0)
```

**Comment by jbenet** [comment]
awesome. might try grepping just `_ := context.`

**Comment by cryptix** [comment]
agreed :)

rebased btw

**Comment by jbenet** [comment]
@cryptix which PR?

**Comment by cryptix** [comment]
it's still a branch only - I guess I can open one now.

**Comment by cryptix** [comment]
closing in favor of #878.
