### ISSUE TITLE
Updating the Webui

### ISSUE THREAD

**Issue by travisperson** [jbenet/go-ipfs#825]
With the recent changes to the webui I think some discussion needs to go into how going about updating the webui should be done.

There are a few things that came up to me as red flags and something that should be looked at before #824. 

In the current pull request for the webui (Though I don't suspect @davidhampgonsalves of any malicious intent), we really have no idea what is behind the hash as of right now or what it was build from. 

At a glance we could see if it's the webui by requesting the hash, but we'd need to do a full code audit of the bundled js to really understand whats happening under the hood.

A few things I think should happen for each update to the webui into IPFS.

1. The webui hash should only be updated by core contributing members
2. The hash should come from master of the ipfs-webui repo.
3. A git commit hash should be included in each build of the webui.

I think it's important for an object that has access to the API be verified in someway. With this we should be able to checkout the ipfs-webui and be able to find the exact code that a particular webui was built from, and then be able to verify it by `make publish`.

Step 1 could be removed, as core members will be merging. They can verify the hash by steps 3, and checking out the code at that commit hash and running `make publish`.

.cc @whyrusleeping @jbenet

**Comment by whyrusleeping** [comment]
referencing #818

**Comment by jbenet** [comment]
@travisperson agreed with every single point above. We should distill this down to a checklist of steps for the core contributor to take, and automate as much as possible. Maybe it can be a `publish` script in `ipfs-webui` that guides the contributor step by step? (triggered with `make publish`).

**Comment by travisperson** [comment]
*Here is a basic proposal of the steps required to publish a new webui.*

---

**Publishing an update to the IPFS Webui**

1. Checkout a clean `master` branch of the [ipfs-webui](https://github.com/protocol/ipfs-webui).
  * Do not have any untracked files that may be pulled into a build
    * These are file such as in `./js`, `./static`, `./less`, `./html`
  * Cloning down a new repo is a good way to make sure you have a clean branch.
2. Run `make publish`
  * This will publish a new build of the webui to ipfs.
    * Build is made by running the gulp `build` task
  * In this process the current git commit hash will be stored to a file on the root of the build directory `git show -q > build/git-version`

**Verifying a IPFS Webui**
Once the above steps are done above, we should be able to verify that the requested webui hash to be merged into ipfs is indeed valid and came from the `ipfs-webui` repository.

1. Resolve the hash, and get the `git-version` file from it.
  * `ipfs cat <hash>/git-version`
2. Checkout the git commit
3. Verify that there are no untracked files or modifications.
  * This is to ensure that the publish step below is working with the same tree.
4. Run `make publish`
5. Verify the produced hash matches.

---

These are the steps I think should be taken to create, and verify a webui before it is merged into ipfs. To implement this all we could really need is to add the `git show -q > build/git-version` step to `make publish`. We could also setup the verification to be automated.

**Comment by whyrusleeping** [comment]
The issue with this is that the files may all be exactly the same, but the git repository might be slightly different. Even checking out a different branch wont ensure ipfs gives the same hash. We need to either delete the `.git` folder, or somehow tell ipfs to ignore it.

**Comment by travisperson** [comment]
Already handled by the [gulp script](https://github.com/protocol/ipfs-webui/blob/master/Makefile#L14). It create a directory called build with all the correct files move.

**Comment by whyrusleeping** [comment]
Oh, thats perfect then!

**Comment by BrendanBenshoof** [comment]
Warning! The Sharness test in pull #823 needs updating when the webUI is updated.

**Comment by jbenet** [comment]
This is done. would be good to add a doc for it.
