### ISSUE TITLE
Unable to install on OSX 10.7.5

### ISSUE THREAD

**Issue by harlantwood** [jbenet/go-ipfs#828]
Caveat: I am a go beginner.  I had an old version of go.  I reinstalled from https://storage.googleapis.com/golang/go1.4.2.darwin-386-osx10.6.pkg

Here's what went down:

```
$ go version
go version go1.4.2 darwin/386
$ go get -u github.com/jbenet/go-ipfs/cmd/ipfs
# github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-reuseport/poll
gocode/src/github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-reuseport/poll/poll_bsd.go:24: cannot use uint64(fd) (type uint64) as type uint32 in field value
$ ipfs
-bash: ipfs: command not found
```

Any advice much appreciated.  Your project is awesome BTW.

**Comment by cryptix** [comment]
Hey,

thanks for the report. Does OSX 10.7.5 require you to run 386? The amd64 version should work.

If so we need to to update `jbenet/go-reuseport` to support 386 darwin. Should be a pretty simple fix but sadly I don't have access to a 32bit system right now to test it directly.
Would you be willing to test it if I made a custom build? I made a really dirty quick fix but I only tested it on 64bit. You can download it [here](http://mars.i.ipfs.io:8080/ipfs/QmUoXH28zJmxbMTokZRMNhauAeJEmn62SvH3jy3DYjda2k/ipfs_darwin_386.zip) if you want.

**Comment by whyrusleeping** [comment]
Yeah, thanks for this report. If you could stick around and help us test a fix to reuseport, that would be great. reuseport is our own custom network layer that we are using instead of go/net because go/net doesnt allow you to set the reuseport flag on opening sockets.

**Comment by harlantwood** [comment]
Ahem.  So I don't have a 32 bit computer either.  I installed the 64 bit go and it works fine.  My apologies.

**Comment by cryptix** [comment]
@harlantwood don't worry :) you made us notice this issue, it also exists on other 32bit systems.

**Comment by jbenet** [comment]
@cryptix are you sure it exists? because i had this weird thing happen. moving from go1.3 -> go1.4 made this very compile error disappear in a 32bit system. i can give you access to it to test if wanted.

**Comment by cryptix** [comment]
> are you sure it exists?

yup. I can trigger it locally by running `GOOS=darwin GOARCH=386 go build` and apart form other *gooddies* (separate issues later) from @Luzifer's [buildlog](http://gateway.ipfs.io/ipfs/QmYX1E1znGRGJntcyPdGEN91BKTcV4m7JBhHW2p48k7ecu) we have the exact same error also on: dragonfly-386, freebsd-{386,arm}, openbsd-386 and netbsd-{386,arm}.

plan9 and solaris also have other funky errors.. :)

**Comment by jbenet** [comment]
yeah after our discussion and the earth fail...
