### ISSUE TITLE
Better error message for when content of hashes is not expected format

### ISSUE THREAD

**Issue by BrendanBenshoof** [jbenet/go-ipfs#831]
"vague sudo-bash"

    hashid = cat | ipfs block
    ipfs cat $hashid

results in:

    Error: Unmarshal failed. proto: illegal wireType 7

Expected:
    Error: The content addressed is not a MerkleDAG

**Comment by whyrusleeping** [comment]
Thanks for reporting this! This needs to be wired down through the merkledag parsing done in DagReader.

**Comment by whyrusleeping** [comment]
Fixed with #832
