### ISSUE TITLE
Recursively pinned objects can not be removed by pressing x in the webui.

### ISSUE THREAD

**Issue by headbite** [jbenet/go-ipfs#850]
Files that are pinned using "ipfs pin add -r hash" can not be removed from the webui. Files pinned without -r work fine in the webui. 

Agent Version: go-ipfs/0.2.3
Protocol Version: ipfs/0.1.0

**Comment by jbenet** [comment]
maybe this should go in https://github.com/protocol/ipfs-webui/ -- cc @mappum thoughts?

**Comment by jbenet** [comment]
moved to https://github.com/protocol/ipfs-webui/issues/21
