### ISSUE TITLE
Races in daemon shutdown

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#854]
Ran a daemon that was build with `-race` and upon shutting it down, received these: https://gist.github.com/whyrusleeping/edd64b6efc5a10292c5f

**Comment by kkoroviev** [comment]
When an interrupt happens, [`GetNode()`](https://github.com/jbenet/go-ipfs/blob/master/cmd/ipfs/main.go#L484) gets called. `GetNode()` always calls [`ConstructNode`](https://github.com/jbenet/go-ipfs/blob/master/cmd/ipfs/main.go#L484), which is a part of the `Context` struct.

Here is the most interesting part: [`daemonFunc()`](https://github.com/jbenet/go-ipfs/blob/master/cmd/ipfs/daemon.go#L80) reassigns [`ConstructNode`](https://github.com/jbenet/go-ipfs/blob/master/cmd/ipfs/daemon.go#L159). Now the interrupt handler may call either the old or the new version of `ConstructNode`. If an interrupt happens during the time when the daemon is just starting up (before we get `API server listening on /ip4/127.0.0.1/tcp/5001`), then the old version of `ConstructNode` gets called. If it happens after, the new version is the one to be called.

**Comment by whyrusleeping** [comment]
@kkoroviev thats moderate-to-severely scary.

**Comment by jbenet** [comment]
main/daemon connection is severely scary. desperately needs fixing.

**Comment by kkoroviev** [comment]
By the way, `GetNode()` doesn't even consider what to do if two or more goroutines call it simultaneously. I can imagine how confused `GetNode()` becomes when someone changes `ConstructNode` right before her (or his, or its) eyes.

**Comment by kkoroviev** [comment]
Do we really need [`NewNodeBuilder`](https://github.com/jbenet/go-ipfs/blob/master/cmd/ipfs/daemon.go#L128) when `ConstructNode` is supposed to take care of building new nodes?

**Comment by whyrusleeping** [comment]
`NewNodeBuilder` is the new interface for constructing an ipfs node. We are deprecating any other methods as they are clunky and hard to use right.

**Comment by jbenet** [comment]
@kkoroviev there's a lot of vestigial stuff in the codebase-- `ConstructNode` is going away for `NewNodeBuilder`, the main/daemon setup is kind of a disaster, so it's taken us time to get there. We may attack that soon.

**Comment by kkoroviev** [comment]
@jbenet @whyrusleeping

Would like your comments.

**Comment by jbenet** [comment]
sorry @kkoroviev -- thanks for pinging. will CR right after 889

**Comment by kkoroviev** [comment]
@whyrusleeping

Is everything okay now?

**Comment by whyrusleeping** [comment]
@kkoroviev Yeah! it looks like the races I was seeing are gone now, thanks!
