### ISSUE TITLE
'addCloser' in core.go `teardown()` incorrect

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#855]
the method `teardown()` on the `core.IpfsNode` has a function named `addCloser` that looks like this:
```
    addCloser := func(c io.Closer) { // use when field may be nil
		if c != nil {
			closers = append(closers, c)
		}
	}
```
The issue is that if i pass `MyCloserType(nil)` into it, the parameter `c` will be a non-nil closer interface pointing to my nil object. Which wont prevent it from being added to the list and called.

**Comment by whyrusleeping** [comment]
@jbenet in case the flood of responses on my PR get a bit lost, just wanted to draw your attention here.

**Comment by jbenet** [comment]
Oh interesting-- i see. let's remove it then
