### ISSUE TITLE
Idea: integrate with XIA (eXpressive Internet Architecture)

### ISSUE THREAD

**Issue by darkstar** [jbenet/go-ipfs#884]
It would be really cool if ipfs worked with (or rather, over) the new XIA network architecture. Maybe you could explore the possibilities...

See here for details on XIA: http://www.cs.cmu.edu/~xia/

**Comment by jbenet** [comment]
@darkstar yeah, ipfs will work well over XIA, NDN, etc. once those networks are actually needed, we can write transports + routing systems for them. (ipfs is highly modular so this isn't hard)

**Comment by jbenet** [comment]
I'll close this issue for now until people have a concrete need for XIA -- i.e. they use a XIA stack and want  to get ipfs working on it asap.
