### ISSUE TITLE
Fix or discard t0060-daemon.sh?

### ISSUE THREAD

**Issue by chriscool** [jbenet/go-ipfs#886]
t0060 still starts with:

```
echo "currently skipping 'Test daemon command', until we find a better way to wait."
exit 0
```

Now that pollEndpoint is used in test-lib.sh, should t0060 be fixed using it or should it be discarded?

**Comment by whyrusleeping** [comment]
I think `t0060` should be fixed, its a good set of tests to have (i think?)

**Comment by jbenet** [comment]
Agreed, i think we should fix it. It's important we dont break the init functionality of the daemon, as lots of people's scripts and dockerfiles now use it.

**Comment by chriscool** [comment]
Ok, I will have a look at fixing it in the next weeks.

**Comment by chriscool** [comment]
Let's close this issue as the PR to reactivate t0060 is merged.
