### ISSUE TITLE
go get windows: undefined: listenStream 

### ISSUE THREAD

**Issue by SimonDanisch** [jbenet/go-ipfs#894]
Hi there,
just wanted to try out go-ipfs and run into this:
```cmd
C:\Users\Sim\Downloads\GoSource\pkg>go get -u github.com/jbenet/go-ipfs/cmd/ipfs

# github.com/jbenet/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-reuseport\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\github.com\jbenet\go-reus
eport\available_unix.go:68: undefined: listenStream\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\github.com\jbenet\go-reus
eport\impl_windows.go:20: available redeclared in this block
        previous declaration at ..\src\github.com\jbenet\go-ipfs\Godeps\_workspa
ce\src\github.com\jbenet\go-reuseport\available_unix.go:50\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\github.com\jbenet\go-reus
eport\interface.go:50: undefined: listenStream\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\github.com\jbenet\go-reus
eport\interface.go:61: undefined: listenPacket\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\github.com\jbenet\go-reus
eport\opts_posix.go:22: cannot use fd (type int) as type syscall.Handle in argum
ent to syscall.SetsockoptInt\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\github.com\jbenet\go-reus
eport\opts_posix.go:34: cannot use fd (type int) as type syscall.Handle in argum
ent to syscall.SetsockoptLinger
# github.com/jbenet/go-ipfs/Godeps/_workspace/src/bazil.org/fuse\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\bazil.org\fuse\fuse.go:10
84: undefined: attr\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\bazil.org\fuse\fuse_kerne
l.go:152: undefined: syscall.O_ACCMODE\src\github.com\jbenet\go-ipfs\Godeps\_workspace\src\bazil.org\fuse\fuse_kerne
l.go:378: undefined: attr
```

**Comment by whyrusleeping** [comment]
Hrm... Thanks for this! looks like we have some interesting things going on. First, its looking into a `_unix.go` file, which shouldnt happen on windows...  @jbenet more reuseport fun in here!

**Comment by jbenet** [comment]
yeah, this is the main remaining problem to get it to build in windows.

btw, even after we build it on windows, i can almost guarantee we do non-windows friendly things with file paths, etc. getting to windows support is likely more than just building.

@SimonDanisch in the meantime, may be worth trying out ipfs in a vm. 

I should mention there's a boot-to-ipfs vm floating around. I use this makefile to make it: https://gist.github.com/jbenet/76afa70955910a2ed097 which uses a mounted ipfs to fetch it lazily. You'll want to just download the vm first from the gateway (since you dont have ipfs :] ), it should be downloadable from: http://gateway.ipfs.io/ipfs/QmdTmSQtCz9D6vt2AbvQkYo3edFcTYoU7FDmDD7bPWDccA/ipfs.iso (~26MB) and then use virtualbox to boot the iso (see the makefile)

**Comment by SimonDanisch** [comment]
Thanks! Well I got ipfs to run on ubuntu, so I guess the VM path isn't really worth it ;)
Please let me know if there's anything I can do to help you get this to run on windows!

**Comment by jbenet** [comment]
@SimonDanisch we should make an issue (maybe one already exists) about it, outline the things in a checklist and then take care of them. first up is fixing https://github.com/jbenet/go-reuseport i believe

**Comment by slothbag** [comment]
I took a look at go-reuseport on windows.. impl_unix.go is like 360 lines long, impl_windows.go is only 20 lines.. So impl_windows has yet to be implemented?

Most of the errors stem from the fact that impl_windows.go is missing a bunch of functions.  But if you put the functions in there then I get compile errors about function re-declaration.  Does the code need some refactoring here?

**Comment by cryptix** [comment]
@SimonDanisch if you feel experimental, we now have a `windows` branch :smile:. See #943 for more infos about known issues and how to get it running.

**Comment by cryptix** [comment]
Closing this in favor of #959.
