### ISSUE TITLE
Build on Windows?

### ISSUE THREAD

**Issue by garyhodgson** [jbenet/go-ipfs#9]
Hi - as already mentioned in https://github.com/jbenet/go-ipfs/pull/8#issuecomment-49886962 it appears that the fuse project will not compile on Windows.  I get the following error when attempting ```go get ./...```:

```
  # bazil.org/fuse
  ..\..\..\..\..\bazil.org\fuse\fuse.go:985: undefined: attr
  ..\..\..\..\..\bazil.org\fuse\fuse_kernel.go:314: undefined: attr
```
This comment at the fuse project from last year seems to indicate that windows is not supported: https://github.com/bazillion/fuse/issues/5#issuecomment-24172348

Windows x64, via cygwin if that is relevant.

**Comment by cryptix** [comment]
Hey everybody. We have the 'nofuse'-build tag to move forward. I'll close this in favor of #959.

**Comment by richardschneider** [comment]
I've create a project to mount IPFS/IPNS on a Windows driver letter.  Its open source at https://github.com/richardschneider/net-ipfs-mount

**Comment by Kubuxu** [comment]
@richardschneider Incredible, thank you so much.
