### ISSUE TITLE
gateway should return 404 instead of 400 on not found

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-ipfs#924]
if i request a path like `localhost:8080/ipfs/SomeHash/apath/that/doesnt/exist` I get a 400 invalid request, instead of the 404 not found i expected.

**Comment by andyleap** [comment]
I'm just getting started with ipfs, but it seems to me like https://github.com/jbenet/go-ipfs/blob/master/core/corehttp/gateway_handler.go#L177-L185 should be simplified down to `webError(w, "Path Resolve error", err, http.StatusBadRequest)`.  That fixes the issue in what seems to me to be the best way.

**Comment by whyrusleeping** [comment]
Well, almost. If i get the error: `no link named "blah" under Qmdudp5XvJr7KrqK6fQ7m2ACStoRxuwfovNHnY6dAAeUis` I want it to return a 404. The problem is that error isnt one of our fancy typed errors, so its not easy to check.

**Comment by andyleap** [comment]
hrm, well, I get that error message, but it's sent by the server as a 404.  That is actually a typed error, as far as I can tell, a `path.ErrNoLink`.

**Comment by cryptix** [comment]
@andyleap @whyrusleeping I think we can close this, yes?

**Comment by andyleap** [comment]
I'm surprised that it didn't get closed by that fixes commit being merged

**Comment by cryptix** [comment]
yep, I guess GH regexes `fixes #number`.
