### ISSUE TITLE
crash when sharing file

### ISSUE THREAD

**Issue by anarcat** [jbenet/go-ipfs#936]
i installed ipfs from here using the instructions on the website in Debian Jessie. Then:

```
ipfs init
ipfs add foo
ipfs daemon
```

at some point the daemon crashed completely with the following backtrace:

http://fpaste.org/199202/raw/

Debian jessie only has Go 1.3, which may be the cause of this problem, but i had been running it at home in 1.3 without too many problems before.

**Comment by jbenet** [comment]
@anarcat yeah, we're on 1.4 now i believe. cc @whyrusleeping

**Comment by whyrusleeping** [comment]
@anarcat that looks like a bug we have fixed. Are you sure youve updated your code?

go 1.3 should work just fine.

**Comment by anarcat** [comment]
i have installed ipfs on this workstation just today, using:

```
go get -u github.com/jbenet/go-ipfs/cmd/ipfs
```

http://ipfs.io/docs/install/ says to use 1.4.

**Comment by whyrusleeping** [comment]
yeah, 1.4 is preferred, but shouldnt cause any issues that I know of.
we run all our unit tests in CI against both 1.3 and 1.4: https://travis-ci.org/jbenet/go-ipfs/builds/54646779

**Comment by whyrusleeping** [comment]
if youre sure youre using latest code then this is in fact a bug, looks like more goprocess fun ( i can just hear @jbenet jumping for joy)

**Comment by anarcat** [comment]
i am pretty sure yes. happy to please @jbenet here of course, any time. ;)

maybe the docs should be clearer about go requirements - for example would it work in 1.0? i assume not... (this, btw, makes ipfs not portable to debian stable right now: https://tracker.debian.org/pkg/golang)

**Comment by jbenet** [comment]
@anarcat that paste disappeared. maybe should add it to some sort of permaweb thing... :)

do you still have it locally, or remember the error?

**Comment by whyrusleeping** [comment]
@jbenet it showed a panic cannot add children after process closed on line 402 of swarm_dial.go

**Comment by jbenet** [comment]
Ahh, i believe i fixed that. that was an actual bug in goprocess. (not the semantics of it being used)

**Comment by jbenet** [comment]
I'll close for now. @anarcat if you can dig up the trace, post. if we run into again, reopen issue.

**Comment by whyrusleeping** [comment]
@jbenet how recently did you fix that? if you read earlier, he was on latest master (after our fix for that)

**Comment by jbenet** [comment]
yesterday: 7777a23
