### ISSUE TITLE
API return values... net.service.handler.HandleMessage

### ISSUE THREAD

**Issue by briantigerchow** [jbenet/go-ipfs#98]
Continuing discussion from https://github.com/jbenet/go-ipfs/pull/69#issuecomment-56246382

> @perfmode good point, that doesn't make much sense. See https://github.com/jbenet/go-ipfs/blob/net/net/service/service.go#L183-L188 Think it should just return a message, and handle/log/whatever its own error?

Yeah. 

If something goes wrong when handling a message, trttd might be to propagate the error upward. ie. an error channel or an error recorder (à la [vitess](https://github.com/youtube/vitess/blob/master/go/vt/concurrency/error_recorder.go)) used by the service (DHT, BitSwap)

**Comment by whyrusleeping** [comment]
closing, no longer relevant
